//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _ {
            get {
                object obj = ResourceManager.GetObject("+", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _PP {
            get {
                object obj = ResourceManager.GetObject("+PP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Acept {
            get {
                object obj = ResourceManager.GetObject("Acept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AceptP {
            get {
                object obj = ResourceManager.GetObject("AceptP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizaar {
            get {
                object obj = ResourceManager.GetObject("Actualizaar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizaarP {
            get {
                object obj = ResourceManager.GetObject("ActualizaarP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar {
            get {
                object obj = ResourceManager.GetObject("Actualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_compra {
            get {
                object obj = ResourceManager.GetObject("Actualizar_compra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_compraP {
            get {
                object obj = ResourceManager.GetObject("Actualizar_compraP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_inventario {
            get {
                object obj = ResourceManager.GetObject("Actualizar_inventario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_inventarioP {
            get {
                object obj = ResourceManager.GetObject("Actualizar_inventarioP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_maquinaria {
            get {
                object obj = ResourceManager.GetObject("Actualizar_maquinaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_maquinariaP {
            get {
                object obj = ResourceManager.GetObject("Actualizar_maquinariaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_proveedor {
            get {
                object obj = ResourceManager.GetObject("Actualizar_proveedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Actualizar_proveedorP {
            get {
                object obj = ResourceManager.GetObject("Actualizar_proveedorP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizarP {
            get {
                object obj = ResourceManager.GetObject("ActualizarP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizarProduccion {
            get {
                object obj = ResourceManager.GetObject("ActualizarProduccion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizarProduccionP {
            get {
                object obj = ResourceManager.GetObject("ActualizarProduccionP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizarVenta {
            get {
                object obj = ResourceManager.GetObject("ActualizarVenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActualizarVentaP {
            get {
                object obj = ResourceManager.GetObject("ActualizarVentaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActulizarEmpleado {
            get {
                object obj = ResourceManager.GetObject("ActulizarEmpleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ActulizarEmpleadoP {
            get {
                object obj = ResourceManager.GetObject("ActulizarEmpleadoP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Adv {
            get {
                object obj = ResourceManager.GetObject("Adv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Agregar {
            get {
                object obj = ResourceManager.GetObject("Agregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Agregar_empleado {
            get {
                object obj = ResourceManager.GetObject("Agregar_empleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Agregar_empleadoP {
            get {
                object obj = ResourceManager.GetObject("Agregar_empleadoP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AgregarCliente {
            get {
                object obj = ResourceManager.GetObject("AgregarCliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap asasdasdasd {
            get {
                object obj = ResourceManager.GetObject("asasdasdasd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Atras {
            get {
                object obj = ResourceManager.GetObject("Atras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AtrasP {
            get {
                object obj = ResourceManager.GetObject("AtrasP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Ayuda {
            get {
                object obj = ResourceManager.GetObject("Ayuda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Borde_Text {
            get {
                object obj = ResourceManager.GetObject("Borde Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarCompra {
            get {
                object obj = ResourceManager.GetObject("BuscarCompra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarCompraP {
            get {
                object obj = ResourceManager.GetObject("BuscarCompraP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarEmpleadox {
            get {
                object obj = ResourceManager.GetObject("BuscarEmpleadox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarEmpleadoxP {
            get {
                object obj = ResourceManager.GetObject("BuscarEmpleadoxP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarMaquinaria {
            get {
                object obj = ResourceManager.GetObject("BuscarMaquinaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarMaquinariaP {
            get {
                object obj = ResourceManager.GetObject("BuscarMaquinariaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarMateriaPrima {
            get {
                object obj = ResourceManager.GetObject("BuscarMateriaPrima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarMateriaPrimaP {
            get {
                object obj = ResourceManager.GetObject("BuscarMateriaPrimaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarProveedores {
            get {
                object obj = ResourceManager.GetObject("BuscarProveedores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarProveedoresP {
            get {
                object obj = ResourceManager.GetObject("BuscarProveedoresP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarVentas {
            get {
                object obj = ResourceManager.GetObject("BuscarVentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BuscarVentasP {
            get {
                object obj = ResourceManager.GetObject("BuscarVentasP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cerrar {
            get {
                object obj = ResourceManager.GetObject("Cerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cerrar_sesión {
            get {
                object obj = ResourceManager.GetObject("Cerrar_sesión", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cerrar_sesiónP {
            get {
                object obj = ResourceManager.GetObject("Cerrar_sesiónP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CerrarP {
            get {
                object obj = ResourceManager.GetObject("CerrarP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Compras {
            get {
                object obj = ResourceManager.GetObject("Compras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarCompra {
            get {
                object obj = ResourceManager.GetObject("ConsultarCompra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarEmpleado {
            get {
                object obj = ResourceManager.GetObject("ConsultarEmpleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarMaquinaria {
            get {
                object obj = ResourceManager.GetObject("ConsultarMaquinaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarMateriaPrima {
            get {
                object obj = ResourceManager.GetObject("ConsultarMateriaPrima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarProveedor {
            get {
                object obj = ResourceManager.GetObject("ConsultarProveedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ConsultarVentas {
            get {
                object obj = ResourceManager.GetObject("ConsultarVentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Eli {
            get {
                object obj = ResourceManager.GetObject("Eli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EliP {
            get {
                object obj = ResourceManager.GetObject("EliP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Empleados {
            get {
                object obj = ResourceManager.GetObject("Empleados", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Entendido {
            get {
                object obj = ResourceManager.GetObject("Entendido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EntendidoP {
            get {
                object obj = ResourceManager.GetObject("EntendidoP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FondoSeguridad {
            get {
                object obj = ResourceManager.GetObject("FondoSeguridad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fondoxd {
            get {
                object obj = ResourceManager.GetObject("fondoxd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fondoxd1 {
            get {
                object obj = ResourceManager.GetObject("fondoxd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GenerarReporte {
            get {
                object obj = ResourceManager.GetObject("GenerarReporte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GenerarReporteP {
            get {
                object obj = ResourceManager.GetObject("GenerarReporteP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GestionarVentas {
            get {
                object obj = ResourceManager.GetObject("GestionarVentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Iniciar_Sesión {
            get {
                object obj = ResourceManager.GetObject("Iniciar_Sesión", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Iniciar_SesiónP {
            get {
                object obj = ResourceManager.GetObject("Iniciar_SesiónP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Inventario {
            get {
                object obj = ResourceManager.GetObject("Inventario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Logotipo {
            get {
                object obj = ResourceManager.GetObject("Logotipo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Logotipooo {
            get {
                object obj = ResourceManager.GetObject("Logotipooo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Logotipooo1 {
            get {
                object obj = ResourceManager.GetObject("Logotipooo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Maquinaria {
            get {
                object obj = ResourceManager.GetObject("Maquinaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Min {
            get {
                object obj = ResourceManager.GetObject("Min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MinP {
            get {
                object obj = ResourceManager.GetObject("MinP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap No {
            get {
                object obj = ResourceManager.GetObject("No", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NoP {
            get {
                object obj = ResourceManager.GetObject("NoP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Produccion {
            get {
                object obj = ResourceManager.GetObject("Produccion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ProduccionP {
            get {
                object obj = ResourceManager.GetObject("ProduccionP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Proveedores {
            get {
                object obj = ResourceManager.GetObject("Proveedores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar {
            get {
                object obj = ResourceManager.GetObject("Registrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_compra {
            get {
                object obj = ResourceManager.GetObject("Registrar_compra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_compraP {
            get {
                object obj = ResourceManager.GetObject("Registrar_compraP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_inventario {
            get {
                object obj = ResourceManager.GetObject("Registrar_inventario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_inventarioP {
            get {
                object obj = ResourceManager.GetObject("Registrar_inventarioP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_maquinaria {
            get {
                object obj = ResourceManager.GetObject("Registrar_maquinaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_maquinariaP {
            get {
                object obj = ResourceManager.GetObject("Registrar_maquinariaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_proveedor {
            get {
                object obj = ResourceManager.GetObject("Registrar_proveedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Registrar_proveedorP {
            get {
                object obj = ResourceManager.GetObject("Registrar_proveedorP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarEmpleado {
            get {
                object obj = ResourceManager.GetObject("RegistrarEmpleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarEmpleadoP {
            get {
                object obj = ResourceManager.GetObject("RegistrarEmpleadoP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarP {
            get {
                object obj = ResourceManager.GetObject("RegistrarP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarProduccion {
            get {
                object obj = ResourceManager.GetObject("RegistrarProduccion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarProduccionP {
            get {
                object obj = ResourceManager.GetObject("RegistrarProduccionP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarVenta {
            get {
                object obj = ResourceManager.GetObject("RegistrarVenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RegistrarVentaP {
            get {
                object obj = ResourceManager.GetObject("RegistrarVentaP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Si {
            get {
                object obj = ResourceManager.GetObject("Si", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SiP {
            get {
                object obj = ResourceManager.GetObject("SiP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
